name: 04 - Using Actions

on: workflow_dispatch

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: show me the folders
              run: ls -la


        # 1. Install dependencies of our REACT application
        # 2. Execute automated tests
