name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug}}

on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
            
env:
    MY_WORKFLOW_VAR: "This is a workflow variable"
    MY_OVERRWRITTEN_VAR: "This is a workflow variable that will be overwritten"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "This is a job variable"
            MY_OVERRWRITTEN_VAR: "This is a job variable that will be overwritten"
        steps:
            - name: Display information
              run: |
                echo "Event Name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Workflow: ${{github.workflow}}"
                echo "RUN ID: ${{github.run_id}}"
                echo "RUN NUMBER: ${{github.run_number}}"
            
            - name: Retrieve Varialbes
              run: | 
                echo "Variable value: ${{vars.MY_VAR}}"

            - name: Print Environment Variables
              env:
                MY_OVERWRITTEN_VAR: "step"

              run: |
                echo "Workflow environment variable: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten workflow environment variable: ${{env.MY_OVERRWRITTEN_VAR}}"

            - name: Print Environment Variables overwritten
              run: |
                echo "Workflow environment variable: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten env: ${{env.MY_OVERRWRITTEN_VAR}}"